"""empty message

Revision ID: 0b4496fa0ad6
Revises: 119245aff68f
Create Date: 2022-04-27 21:45:29.743959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4496fa0ad6'
down_revision = '119245aff68f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day_of_meal', sa.Column('cooktime', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day_of_meal', 'cooktime')
    # ### end Alembic commands ###
