"""empty message

Revision ID: 119245aff68f
Revises: c3989e8ae24e
Create Date: 2022-04-27 21:15:43.136180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119245aff68f'
down_revision = 'c3989e8ae24e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_of_meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('image', sa.String(length=300), nullable=True),
    sa.Column('weekday', sa.String(length=50), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('favorite', sa.Column('cooktime', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite', 'cooktime')
    op.drop_table('day_of_meal')
    # ### end Alembic commands ###
