"""empty message

Revision ID: 4b888d477bd1
Revises: 02865ee4198d
Create Date: 2022-04-21 19:01:29.395047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b888d477bd1'
down_revision = '02865ee4198d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('ingredient1', sa.String(length=300), nullable=True))
    op.add_column('post', sa.Column('ingredient2', sa.String(length=300), nullable=True))
    op.add_column('post', sa.Column('ingredient3', sa.String(length=300), nullable=True))
    op.add_column('post', sa.Column('ingredient4', sa.String(length=300), nullable=True))
    op.add_column('post', sa.Column('ingredient5', sa.String(length=300), nullable=True))
    op.add_column('post', sa.Column('directions', sa.String(length=1000), nullable=True))
    op.drop_column('post', 'caption')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('caption', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_column('post', 'directions')
    op.drop_column('post', 'ingredient5')
    op.drop_column('post', 'ingredient4')
    op.drop_column('post', 'ingredient3')
    op.drop_column('post', 'ingredient2')
    op.drop_column('post', 'ingredient1')
    # ### end Alembic commands ###
