"""empty message

Revision ID: ab2b0f07acd9
Revises: 3d8844b5923e
Create Date: 2022-04-23 15:18:14.335921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab2b0f07acd9'
down_revision = '3d8844b5923e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('image', sa.String(length=300), nullable=True),
    sa.Column('ingredient1', sa.String(length=300), nullable=True),
    sa.Column('ingredient2', sa.String(length=300), nullable=True),
    sa.Column('ingredient3', sa.String(length=300), nullable=True),
    sa.Column('ingredient4', sa.String(length=300), nullable=True),
    sa.Column('ingredient5', sa.String(length=300), nullable=True),
    sa.Column('directions', sa.String(length=1000), nullable=True),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('date_saved', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    # ### end Alembic commands ###
