"""empty message

Revision ID: c3989e8ae24e
Revises: ab2b0f07acd9
Create Date: 2022-04-25 17:17:45.937559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3989e8ae24e'
down_revision = 'ab2b0f07acd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('cooktime', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'cooktime')
    # ### end Alembic commands ###
